version: '3.9'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.4
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres-origin:
    image: debezium/postgres:12-alpine
    ports:
     - "6000:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=inventory
  postgres-dest:
    image: debezium/postgres:12-alpine
    ports:
     - "6001:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=history
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
     - "9200:9200"
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false
  connect:
    image: debezium/connect:1.4
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - postgres-origin
     - postgres-dest
     - elastic
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
